server:
  port: 7201

spring:
  datasource:
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=jwt_security;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: terry
    password: 'terry'

  application:
    name: afrocodemy-kyc-local


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true

  mail:
    host: smtp.office365.com
    port: 587
    username: noreply@afrosoft.co.zw
    password: '%$Afro123'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    test-connection: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  main:
    allow-bean-definition-overriding: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


sms:
  username: Devtest
  password: "%Dev@190"
  smsclientid: 2115420437
  senderid: FNB
  gateway: http://196.43.100.53:8901/teleoss/sendsms.jsp
  accountusagetypeid: 1
  unicode: 0
  isallowduplicatemobile: yes

signing:
  key: afrocodemy_default_user

default:
  client:
    id: client_id
    secret: client_secret
    grantTypes: refresh_token,password,client_credentials
    authorities: read,write
    scopes: read,write
    authUrl: /oauth/token

