server:
  port: 7201

spring:
  datasource:
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=jwt_security;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: terry
    password: 'terry'

  application:
    name: afrocodemy-kyc-local


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true

  main:
    allow-bean-definition-overriding: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

signing:
  key: afrocodemy_default_user

default:
  client:
    id: client_id
    secret: client_secret
    grantTypes: refresh_token,password,client_credentials
    authorities: read,write
    scopes: read,write
    authUrl: /oauth/token

